SELECT p.PRODUCT_ID
     , p.PRODUCT_NAME
     , p.PRICE * SUM(o.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER AS o
    INNER JOIN FOOD_PRODUCT AS p ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE o.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY p.PRODUCT_ID
ORDER BY TOTAL_SALES DESC , p.PRODUCT_ID
