SELECT DISTINCT h.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
    LEFT JOIN CAR_RENTAL_COMPANY_CAR AS c ON h.CAR_ID = c.CAR_ID
WHERE CAR_TYPE = '세단'
    AND START_DATE >= '2022-10-01'
ORDER BY h.CAR_ID DESC
