WITH A AS(
    SELECT *
         , ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS row_n
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
    ORDER BY PRICE DESC
)
  
SELECT CATEGORY
     , PRICE AS MAX_PRICE
     , PRODUCT_NAME
FROM A
WHERE row_n=1
