WITH RENT AS(
    SELECT DISTINCT CAR_ID
         , CASE 
            WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN 1
            ELSE 0
           END AS score
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    ORDER BY CAR_ID DESC
)

SELECT CAR_ID
     , CASE
        WHEN SUM(score) = 0 THEN '대여 가능'
        ELSE '대여중'
       END AS AVAILABILITY
FROM RENT
GROUP BY CAR_ID
