SELECT APNT_NO
     , PT_NAME
     , a.PT_NO AS PT_NO
     , a.MCDP_CD AS MCDP_CD
     , DR_NAME
     , APNT_YMD
FROM APPOINTMENT AS a
    LEFT JOIN PATIENT AS p ON a.PT_NO = p.PT_NO
    LEFT JOIN DOCTOR AS d ON a.MDDR_ID = d.DR_ID
WHERE a.MCDP_CD = 'CS'
    AND APNT_YMD BETWEEN '2022-04-13 00:00:00' AND '2022-04-13 23:59:59'
    AND APNT_CNCL_YN = 'N'
ORDER BY a.APNT_YMD
