SELECT CATEGORY
     , SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES AS bs
    LEFT JOIN BOOK AS b ON bs.BOOK_ID = b.BOOK_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY CATEGORY
ORDER BY CATEGORY
